language: rust

matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check
        - cargo build
        - cargo test
    - rust: nightly
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
        - cargo build
        - cargo test
